version: '2'
# define all services
services:
  # our service is called CakePHP ;-)
  cakephp:
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4001:80"
    # we mount the working dir into the container, handy for development 
    volumes:
      - $PWD/:/var/www/html/
    environment:
      - SECURITY_SALT=ashjg23697sds97139871298ashk  
      - MYSQL_URL=10.10.10.19:7007
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root