version: '3'
# define all services
services:
  # our service is called CakePHP ;-)
  cakephp:
    container_name: cakePhp
    # we want to use the image which is build from our Dockerfile
    build: 
      context: .
      dockerfile: Dockerfile
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4002:80"
    # we mount the working dir into the container, handy for development 
    volumes:
      - $PWD/projects:/var/www/html/
    environment:  
      - MYSQL_URL=10.10.10.19:7007
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    networks:
      - cakePHP

networks: 
  cakePHP: